name: ArenaSetupAssistant
version: '${project.version}'
main: org.jwix777.ArenaSetupAssistant.ArenaSetupAssistant
commands:
  asa:
    description: Opens gui
    usage: "/<command>"
    aliases:
      - arenasetupassistant